README.md

/kind cleanup
Fixes #
```release-note
NONE
```

chore: update CI and goreportcard badge

---

pkg/executor/observabilityactionpolicy_controller.go
pkg/fetch/fetch.go
tests/install-infra.sh

/kind bug
e2e script error exit.
Fixes #
```release-note
NONE
```

fix: e2e script error exit

---

cmd/executor/main.go
pkg/common/controller_options.go
pkg/common/flags.go
pkg/common/klog.go
pkg/common/rest_config.go
pkg/executor/observabilityactionpolicy_controller.go
vendor/k8s.io/klog/v2/klogr/README.md
vendor/k8s.io/klog/v2/klogr/klogr.go
vendor/modules.txt

feature
#7 
Fixes #7 
```release-note
NONE
```

context logger with klog, flag parsing plugin

---

pkg/executor/observabilityindicant_controller.go

/kind cleanup
Another controller of the executor is still using `klog`, adjust it.
Fixes #
```release-note
NONE
```

context logger with klog

---

charts/arbiter/Chart.yaml

/kind bug
follow the semantic version definition.
Fixes #
```release-note
NONE
```

update charts version

---

charts/arbiter/templates/deployment-metric-server.yaml
charts/arbiter/templates/deployment-prometheus.yaml
manifests/install/observer/observer-metric-server.yaml
manifests/install/observer/observer-prometheus.yaml

/kind feature
The current observer component does not have a `livesnessProbe` configured.
Fixes #
```release-note
```

add liveness probe for observer

---

.golangci.yaml
cmd/executor/main.go
pkg/common/controller_options.go
pkg/common/klog.go
pkg/common/rest_config.go
pkg/controller/controller.go
pkg/executor/observabilityactionpolicy_controller.go

/kind cleanup
Fixes #
```release-note
NONE
```

fix: some issue found by golangci-lint

---

.github/auto_request_review.yml
.github/workflows/auto_assign_reviewers.yml

/kind cleanup
Fixes #
```release-note
NONE
```

fix: make auto request review rework

---

pkg/controller/controller.go

/kind feature
enhance code readability
Fixes #
```release-note
NONE
```

enhance code readability

---

charts/arbiter/templates/deployment-metric-server.yaml
charts/arbiter/templates/deployment-prometheus.yaml
charts/arbiter/templates/deployment.yaml
manifests/install/executor/executor-resource-tagger.yaml

Update yaml files format and remove some config
Fixes #
```release-note
```

Update yaml files format and remove some config

---

charts/arbiter/Chart.yaml

/kind feature
add icon to chart package.
Fixes #
```release-note
NONE
```

add icon to chart package

---

pkg/controller/controller_test.go

/kind bug
observer controller unit test failed.
Fixes #
```release-note
NONE
```

fix: controller unit test failed

---

hack/lib/golang.sh

/kind cleanup
Fixes #
```release-note
NONE
```

cleanup: update golang.sh

---

.golangci.yaml
pkg/controller/controller.go
pkg/executor/observabilityactionpolicy_controller.go
pkg/extend/manager/manager.go

/kind feature
Inspired by https://github.com/kubernetes/kubernetes/pull/113256:
Add https://github.com/go-critic/go-critic to linter.
Fixes #
```release-note
NONE
```

feat: add linter gocritic

---

pkg/controller/controller.go
pkg/controller/helper.go

/kind cleanup
Split code. Improve code readability.
Fixes #
```release-note
NONE
```

split code

---

.golangci.yaml

/kind cleanup
Fixes #
https://github.com/kube-arbiter/arbiter/pull/31 should marge first, and retest this one.
```release-note
NONE
```

fix: make linter contextcheck work

---

.github/sync.yml
.github/workflows/sync.yml

/kind feature
Fixes #
```release-note
NONE
```

feat: add workflow to sync file to pre branch

---

.github/sync.yml

/kind cleanup
Fixes #
```release-note
NONE
```

cleanup: update sync file list

---

pkg/utils/util_test.go

/kind feature
add test cases for utils package.
Updated #28 
```release-note
NONE
```

feat: add test cases for utils package

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/e2e.yml

/kind feature
same with #55 
Fixes #
```release-note
NONE
```

feat: add concurrency args in github action

---

charts/arbiter/README.md

/kind bug
update readme of the arbiter chart.
Fixes #
```release-note
NONE
```

update readme of the arbiter chart

---

cmd/observer/main.go
pkg/observer/helper.go
pkg/observer/observer.go
pkg/observer/observer_test.go

/kind cleanup
Fixes #
controller renamed to observer
```release-note
NONE
```

controller renamed to observer

---

Makefile
cmd/scheduler/main.go
cmd/scheduler/main_test.go
hack/fix-golang-lint-error.sh
hack/tools/tools.go
pkg/scheduler/manager/manager.go
pkg/scheduler/manager/metrics.go
pkg/scheduler/scheduler.go
tests/prepare-k8s.sh

/kind feature
Fixes #71 #69 #62
```release-note
NONE
```

Synced files with main and update

---

pkg/scheduler/manager/manager.go
pkg/scheduler/scheduler.go

/kind cleanup
Fixes #
```release-note
NONE
```

cleanup: rename Manager1 to manager

---

doc/install.md

/kind bug
update the image in the doc.
Fixes #
```release-note
```

fix: update the image in the doc

---

tests/e2e/observer_test.go
tests/e2e/util_test.go

/kind bug
fix wrong test cases.
Fixes #
```release-note
NONE
```

fix wrong test cases

---

tests/install-infra.sh

/kind bug
Fixes #82 
```release-note
NONE
```

fix: use cert-manager v1.8.2 in k8s 1.20-

---

.github/sync.yml

/kind bug
It looks like the previous automatic sync always updated the files that needed to be ignored, the reason may be due to the missing `/`
Fixes #
```release-note
NONE
```

update auto-sync config

---

hack/lib/golang.sh

ref: https://github.com/mvdan/sh/pull/849
/kind cleanup
Fixes #
```release-note
NONE
```

Simplify unset-or-null expansions after shfmt update to 3.6.0

---

.golangci.yaml

/kind bug
For #107 
```release-note
NONE
```

test: Temporarily disable gci in golangci-lint testing

---

tests/e2e/util_test.go
tests/e2e/webhook_test.go
tests/install-infra.sh

/kind cleanup
1. different versions of kubectl have different values for the cascade parameter.
2. bash sytax fix.
3. the k8s version determination is abstracted as a function in the go test file.
Fixes #
```release-note
NONE
```

fix: some issue in test

---

pkg/observer/observer.go

/kind cleanup
Fixes #
```release-note
none
```

fix: optimize logic

---

tests/e2e/webhook_test.go
tests/install-infra.sh
tests/prepare-k8s.sh

/kind failing-test
Fixes #
```release-note
```

test: fix overcommit test
